# Generated by Django 3.2.7 on 2021-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_finish_time',
            field=models.DateTimeField(),
        ),
    ]
