# Generated by Django 3.2.7 on 2021-09-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_estimated_finish_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='body',
            new_name='text',
        ),
    ]
